#!/usr/bin/env python3
"""Slice the embedding MLP weights into an int16 header for the AIE kernel.

The embedding is  Linear(5->16) + LN + ReLU  ->  Linear(16->16) + LN + ReLU
->  Linear(16->16), applied to the 12 jets of an event. Scales follow
attn_aie_types.h: data and biases at Q6.9, weight matrices at Q3.12.

The input BatchNorm in the export is the identity (mean 0, var 1, weight 1,
bias 0) so nothing is fused into the first layer; the script checks that and
refuses if a future export changes it.

Layer 0's K is padded from 5 to 8 because gemm_pk needs K a multiple of 4;
the padding columns are zero and cost nothing at run time.
"""
import numpy as np, os

P = "/home/snehadri/repos/unsupervised-search/phase3_export_retrained/weights"
OUT = "/home/snehadri/repos/aie-unsupervised-search/src/attn_block_aie/kernels/weights/embed_weights.h"
DATA_FRAC, W_FRAC = 9, 12
E, K0P = 16, 8

ld = lambda n: np.load(f"{P}/{n}.npy")
for n, want in (("embed_input_bn_running_mean", 0.0), ("embed_input_bn_running_var", 1.0),
                ("embed_input_bn_weight", 1.0), ("embed_input_bn_bias", 0.0)):
    a = ld(n)
    assert np.allclose(a, want), f"{n} is not the identity ({a}); fuse it into layer 0 first"

def q(a, frac):
    v = np.rint(np.asarray(a, np.float64) * (1 << frac))
    assert np.abs(v).max() <= 32767, f"overflow at Q.{frac}: {np.abs(a).max()}"
    return v.astype(np.int16)

W0, b0 = ld("embed_net_0_weight"), ld("embed_net_0_bias")      # (16,5), (16)
g1, B1 = ld("embed_net_1_weight"), ld("embed_net_1_bias")      # LN after layer 0
W3, b3 = ld("embed_net_3_weight"), ld("embed_net_3_bias")      # (16,16)
g4, B4 = ld("embed_net_4_weight"), ld("embed_net_4_bias")      # LN after layer 1
W6, b6 = ld("embed_net_6_weight"), ld("embed_net_6_bias")      # (16,16)

W0p = np.zeros((K0P, E), np.float64)      # gemm_pk wants B as [K][N]
W0p[:W0.shape[1], :] = W0.T

def emit(f, name, arr, frac):
    v = q(arr, frac).ravel()
    # alignas(16) is REQUIRED: gemm_pk loads the weight operand with
    # aie::load_v<8> (16 bytes) and an unaligned load returns wrong data on the
    # real core while x86sim happily reads it. Without this the kernel matched
    # the golden in x86sim to 0.006 and was off by 1.44 in aiesimulator.
    f.write(f"alignas(16) static const int16 {name}[{v.size}] = {{\n")
    for i in range(0, v.size, 16):
        f.write("    " + ", ".join(f"{x:6d}" for x in v[i:i+16]) + ",\n")
    f.write("};\n\n")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("// Generated by scripts/export_embed_weights_aie.py -- do not edit.\n")
    f.write(f"// Embedding MLP: 5 -> {E} -> {E} -> {E} over N_MAX jets.\n")
    f.write(f"// Weight matrices Q3.{W_FRAC} stored as [K][N]; biases and LN at Q6.{DATA_FRAC}.\n")
    f.write("// Layer 0's K is padded 5 -> 8 with zeros for gemm_pk.\n#pragma once\n\n")
    emit(f, "embed_W0", W0p, W_FRAC);  emit(f, "embed_b0", b0, DATA_FRAC)
    emit(f, "embed_ln0_g", g1, DATA_FRAC); emit(f, "embed_ln0_b", B1, DATA_FRAC)
    emit(f, "embed_W1", W3.T, W_FRAC); emit(f, "embed_b1", b3, DATA_FRAC)
    emit(f, "embed_ln1_g", g4, DATA_FRAC); emit(f, "embed_ln1_b", B4, DATA_FRAC)
    emit(f, "embed_W2", W6.T, W_FRAC); emit(f, "embed_b2", b6, DATA_FRAC)
print("wrote", OUT)
for n, a in (("W0", W0), ("W1", W3), ("W2", W6)):
    print(f"  {n}: max |w| = {np.abs(a).max():.3f}")
