#!/usr/bin/env python3
"""Slice the pairwise MLP weights into an int16 header for the AIE kernels.

The pairwise bias network is  Linear(3->16) + LN + ReLU  ->  Linear(16->16) + LN
+ ReLU  ->  Linear(16->16) + LN + ReLU  ->  Linear(16->1), applied to the 144
jet pairs of an event. Scales follow attn_aie_types.h: data, biases and LN at
Q6.9, weight matrices at Q3.12, the same as the embedding export.

Layer 0's K is padded 3 -> 4 (gemm_pk needs K a multiple of 4); the last
layer's N is padded 1 -> 8 (gemm_pk needs N a multiple of 8) with zero
columns. Neither padding changes a result.
"""
import numpy as np, os

P = "/home/snehadri/repos/unsupervised-search/phase3_export_retrained/weights"
OUT = "/home/snehadri/repos/aie-unsupervised-search/src/attn_block_aie/kernels/weights/pairwise_weights.h"
DATA_FRAC, W_FRAC = 9, 12
H = 16

ld = lambda n: np.load(f"{P}/{n}.npy")
def q(a, frac):
    v = np.rint(np.asarray(a, np.float64) * (1 << frac))
    assert np.abs(v).max() <= 32767, f"overflow at Q.{frac}: {np.abs(a).max()}"
    return v.astype(np.int16)

W0, b0 = ld("mlp_net_0_weight"), ld("mlp_net_0_bias")      # (16,3), (16)
g1, B1 = ld("mlp_net_1_weight"), ld("mlp_net_1_bias")
W3, b3 = ld("mlp_net_3_weight"), ld("mlp_net_3_bias")      # (16,16)
g4, B4 = ld("mlp_net_4_weight"), ld("mlp_net_4_bias")
W6, b6 = ld("mlp_net_6_weight"), ld("mlp_net_6_bias")      # (16,16)
g7, B7 = ld("mlp_net_7_weight"), ld("mlp_net_7_bias")
W9, b9 = ld("mlp_net_9_weight"), ld("mlp_net_9_bias")      # (1,16), (1)

W0p = np.zeros((4, H)); W0p[:3, :] = W0.T                  # [K][N], K padded to 4
W9p = np.zeros((H, 8)); W9p[:, 0] = W9[0]                  # [K][N], N padded to 8
b9p = np.zeros(8); b9p[0] = b9[0]

def emit(f, name, arr, frac):
    v = q(arr, frac).ravel()
    f.write(f"alignas(16) static const int16 {name}[{v.size}] = {{\n")
    for i in range(0, v.size, 16):
        f.write("    " + ", ".join(f"{x:6d}" for x in v[i:i+16]) + ",\n")
    f.write("};\n\n")

with open(OUT, "w") as f:
    f.write("// Generated by scripts/export_pairwise_weights_aie.py -- do not edit.\n")
    f.write("// Pairwise bias MLP: 3 -> 16 -> 16 -> 16 -> 1 over the 144 jet pairs.\n")
    f.write("// Weight matrices Q3.12 stored as [K][N]; biases and LN at Q6.9.\n")
    f.write("// Layer 0's K is padded 3 -> 4, the last layer's N 1 -> 8, with zeros.\n#pragma once\n\n")
    emit(f, "pair_W0", W0p, W_FRAC); emit(f, "pair_b0", b0, DATA_FRAC)
    emit(f, "pair_ln0_g", g1, DATA_FRAC); emit(f, "pair_ln0_b", B1, DATA_FRAC)
    emit(f, "pair_W1", W3.T, W_FRAC); emit(f, "pair_b1", b3, DATA_FRAC)
    emit(f, "pair_ln1_g", g4, DATA_FRAC); emit(f, "pair_ln1_b", B4, DATA_FRAC)
    emit(f, "pair_W2", W6.T, W_FRAC); emit(f, "pair_b2", b6, DATA_FRAC)
    emit(f, "pair_ln2_g", g7, DATA_FRAC); emit(f, "pair_ln2_b", B7, DATA_FRAC)
    emit(f, "pair_W3", W9p, W_FRAC); emit(f, "pair_b3", b9p, DATA_FRAC)
print("wrote", OUT)
