#include <cstdio>
#include <cmath>
int main() {
    printf("#ifndef EXP_LUT_ROM_H\n#define EXP_LUT_ROM_H\n");
    printf("// generated by scripts/gen_exp_lut.cpp -- exp_t(expf(i/32 - 8)) for i=0..256,\n");
    printf("// pre-truncated to exp_t's 22 fractional bits (AP_TRN) so the ROM entry is\n");
    printf("// bit-identical to what (exp_t)expf((float)x) produced for every\n");
    printf("// representable score_t input in [-8, 0].\n");
    printf("static const exp_t exp_lut_rom[257] = {\n");
    for (int i = 0; i <= 256; i++) {
        float x = i / 32.0f - 8.0f;
        double v = std::floor((double)expf(x) * 4194304.0) / 4194304.0; // 2^22
        printf("    exp_t(%.17g)%s\n", v, i < 256 ? "," : "");
    }
    printf("};\n#endif\n");
    return 0;
}
